#######################################################################################
# A default configuration that will be loaded for all jupyter books
# See the documentation for help and more options: 
# https://jupyterbook.org/customize/config.html

#######################################################################################
# Book settings
title                       : my-book  # The title of the book. Will be placed in the left navbar.
author                      : Marilyn Waldman  # The author of the book
copyright                   : "2021"  # Copyright year to be placed in the footer
logo                        : logo.png  # A path to the book logo  

# Information about where the book exists on the web
repository:
  url                       : https://github.com/marilynwaldman/book 
 
  
launch_buttons:
  colab_url: "https://colab.research.google.com" 
  